### ISSUE TITLE
'Backup' is not working for all the Apps (Its working fine for few apps but getting failed for few apps)

### ISSUE THREAD

**Issue by nirav-appveen** [appveen/datastack-backup-restore#4]
'Backup' is not working for all the Apps (Its working fine for few apps but getting failed for few apps).

**Test Data:**
- Env: Bifrost
- App for which Backup is working fine: 'BackUpApp'
- App for which Backup is not working: 'AzureAD'

Please find below image:

![Backup is getting failed for few apps](https://user-images.githubusercontent.com/96046386/177290871-ce17678d-2bd2-444d-9ae4-0f81d0fd2420.jpg)

**Comment by jerrymannel** [comment]
Please download the latest executable. This issue was fixed in #2 and released.

**Comment by nirav-appveen** [comment]
> Please download the latest executable. This issue was fixed in #2 and released.

Still facing this error, tried with the latest version i.e #2

<img width="905" alt="Screenshot 2022-07-05 173016" src="https://user-images.githubusercontent.com/96046386/177473982-504efa00-21a4-4d47-8f7f-af3a3cc8214b.png">
